### ISSUE TITLE
Rest operators not transpiled. This breaks all IE/Edge browsers.

### ISSUE THREAD

**Issue by michaelpumo** [nuxt-community/svg-module#11]
Hi there!

If I use your module and specify an inline SVG (used via components) the build will not transpile the rest operators found in the production/built JS.

I did some reading and found that `vue-svg-loader` does not get transpiled, so I put it in the Nuxt config like so:

```
build: {
    transpile: [
      'vue-svg-loader'
    ]
}
```

With the use of this module, it still does not work or make a difference.

Interestingly, if I simply take the code from your module that you use to override the Webpack config and paste it manually into my Nuxt config (thus bypassing your module) it works.

```
build: {
  transpile: [
    'vue-svg-loader'
  ],
  extractCSS: true,
  extend(config, ctx) {
    if (ctx.isDev && ctx.isClient) {
      config.module.rules.push({
        enforce: 'pre',
        test: /\.(js|vue)$/,
        loader: 'eslint-loader',
        exclude: /(node_modules)/
      })
    }

    const ORIGINAL_TEST = /\.(png|jpe?g|gif|svg|webp)$/
    const REPLACEMENT_TEST = /\.(png|jpe?g|gif|webp)$/
    const rules = config.module.rules
    const svgRules = rules.filter(rule => rule.test.test('.svg'))

    svgRules.forEach((rule) => {
      if (rule.test.source !== ORIGINAL_TEST.source && rule.test.source !== REPLACEMENT_TEST.source) {
        throw new Error("nuxt-svg: Unexpected '.svg' rule in the webpack configuration")
      }

      rule.test = REPLACEMENT_TEST
    })

    const vueSvgLoader = [
      {
        loader: 'vue-svg-loader',
        options: {
          svgo: false
        }
      }
    ]

    if (config.name === 'client') {
      vueSvgLoader.unshift({
        loader: 'babel-loader',
        options: {
          presets: ['@nuxt/babel-preset-app'],
          plugins: ['@babel/plugin-proposal-object-rest-spread']
        }
      })
    }

    const rule = {
      test: /\.svg$/,
      oneOf: [
        {
          resourceQuery: /inline/,
          use: vueSvgLoader
        },
        {
          resourceQuery: /data/,
          loader: 'url-loader'
        },
        {
          loader: 'file-loader'
        }
      ]
    }

    rules.push(rule)
  }
}
```

I'm not sure why this is the case. I would love to just use your module as a dependency for better management but I had to use it manually for it to transpile correctly with Nuxt.

Any idea how this could be resolved?

**Comment by brhx** [comment]
Please can you confirm that the following _doesn't_ cause nuxt to transpile the `vue-svg-loader` module?

```javascript
{
  modules: ['@nuxtjs/svg'],
  build: {
    transpile: ['@nuxtjs/svg']
  }
};
```

Also might be worth seeing if [this solution](https://github.com/visualfanatic/vue-svg-loader/issues/63#issuecomment-460963641) or [this solution](https://github.com/visualfanatic/vue-svg-loader/issues/63#issuecomment-510224230) works?

**Comment by riso348** [comment]
@sam3d Thank you very much! :) i had similar problem with _vue2-leaflet_ plugins even with @babel/plugin-proposal-object-rest-spread in babel config.

For me this works: (nuxt v2.10.2) Maybe it will help someone
**nuxt.config.ts:**
```
build: {
       ...
        transpile: ['vue2-leaflet'],
        babel: {
            babelrc: true,
            configFile: './babel.config.js'
        },
        ...
    }
```

**babel.config.js:**

```
module.exports = function (api) {
    api.cache(true);
    return {
        presets: ['@nuxt/babel-preset-app'],
        plugins: [["@babel/plugin-proposal-object-rest-spread", {"useBuiltIns": true}]]
    };
};
```
