### ISSUE TITLE
Offer to move to nuxt-community

### ISSUE THREAD

**Issue by pi0** [nuxt-community/svg-module#14]
Hi. Just discovered this awesome module. I think other than [svg-sprite-module](https://github.com/nuxt-community/svg-sprite-module) this is a very very useful module which can be more official.

If you wish, here are steps:
- [x] We will send you invitations for GitHub and NPM
- [x] Move the repository to nuxt-community
- [x] A PR to make repo compatible with [module-template](https://github.com/nuxt-community/module-template)
- [ ] Publish under `@nuxtjs` and offer users using the new package. deprecating current one.

--
/cc @galvez @atinux @farnabaz

**Comment by brhx** [comment]
That would be amazing! I would love more exposure for this module so I can have a hand developing it. I am interested in doing this switch, please forward me any details I'll need.

**Comment by pi0** [comment]
@sam3d AWESOME! Would you please accept invitations and move the repository to nuxt-community?

**Comment by brhx** [comment]
Sure thing! Just done it now 😄

**Comment by pi0** [comment]
PR: #16

**Comment by pi0** [comment]
OK now the only remaining part is publishing and deprecate `nuxt-svg` using `npm deprecate` (so users won't keep using outdated package)

You should have published access. An `npm run release` command is also now available to automate release/changelog process.

**Comment by brhx** [comment]
It's been deprecated and been republished under the new namespace!

**Comment by pi0** [comment]
Closing this PR as changes are done. If you wish, you can create a PR to [awesome-nuxt](https://github.com/nuxt-community/awesome-nuxt) listing this module to official section.
