### ISSUE TITLE
inline fails

### ISSUE THREAD

**Issue by ladrua** [nuxt-community/svg-module#18]
Trying to use the inline functionality:
```
import quote from '~/assets/images/quote.svg?inline'
export default {
  components: {
        quote
  }
}
```
And I am getting this error:
```
Module parse failed: Unterminated string constant (24:72) 
File was processed with these loaders: * ./node_modules/vue-svg-loader/index.js 
You may need an additional loader to handle the result of these loaders.
 | ...rest, | }, > children.concat([_c('style',{attrs:{"type":"text/css"}},
[_v(' | .st0{font-family:'TimesNewRomanPS-BoldMT';} | .st1{font-size:144px;} 
```

**Comment by Geminii** [comment]
Hi @ladrua,
Do you have include the module into `nuxt.config.js` ? And install dependencies ?

**Comment by ttillberg** [comment]
Having the same issue. The `<style>` tags within the SVG files seem to be the culprits.

i.e.

```svg
<style type="text/css">
   .st0{fill-rule:evenodd;clip-rule:evenodd;fill:currentColor;}
</style>
```

**Comment by Geminii** [comment]
Yes i got a similar problem too. 
But if you use SVGO, it will compress the file and in theorie it works after this. 
Personnally, i don't use fill on my icon and define it directly on the svg node like this : 

`<AccountIcon class="color-primary" />`

**Comment by ttillberg** [comment]
@Geminii Yes that's cool. The reason I'm pointing this out is because it occurred after upgrading a project that has been working fine so far. I do prefer attributes instead of inline styles otherwise.

**Comment by frbuceta** [comment]
I don't know if it's the same but when I compile nuxt I empty the defs tag

**In developer mode:**
```
<defs>
  <style>.cls-1{fill:#fff;fill-rule:evenodd;}</style>
</defs>
```

**Compiled:**
`<defs></defs>`

**Comment by urbgimtam** [comment]
This is the same issue as #24

**Comment by urbgimtam** [comment]
For reference, you can mitigate this issue by using Illustrator. When exporting the svg, choose 'Inline Style' instead of 'Internal CSS'.

**Comment by Geminii** [comment]
@urbgimtam i don't have access to illustrator, i'm only a poor web developper ^^
To solve this, i test some things.

This one fail : 
```css
<style type="text/css">
   .st0{fill-rule:evenodd;clip-rule:evenodd;fill:currentColor;}
</style>
```

This one works : 
```css
<style type="text/css">.st0{fill-rule:evenodd;clip-rule:evenodd;fill:currentColor;}</style>
```

Probably, need to remove some spaces contains into `style` attribute ?

**Comment by brhx** [comment]
Please use `raw-loader` as outlined [here](https://github.com/nuxt-community/svg-module#raw-loader) to ensure CSS is imported correctly.

**Comment by mrleblanc101** [comment]
I get `Unterminated string constant. (24:44)` when there is CSS in my SVG.
I need the CSS because it's an animation.
Is there a technical reason why `?inline` wouldn't work but `?raw` would ?
I think both should work but there seem to be a bug that need to be fixed.
<img width="1012" alt="Capture d’écran, le 2022-06-15 à 22 20 53" src="https://user-images.githubusercontent.com/17392251/173977416-8d76e238-45a8-43bc-8452-fa29d7ecf12e.png">
<img width="1819" alt="Capture d’écran, le 2022-06-15 à 22 20 55" src="https://user-images.githubusercontent.com/17392251/173977410-e50d7776-22ce-4d24-b1ec-ead099072ef9.png">
.

**Comment by urbgimtam** [comment]
Maybe it is a parsing error related to ' and " ? If so, it would be a bug.
Can't confirm without the actual code.

**Comment by mrleblanc101** [comment]
There is not `'` or `"` in the CSS...

**Comment by urbgimtam** [comment]
Maybe it has to do with class names having an hyphen? On your message error it breaks just before ".test-1".
"Unterminated string" usually refers to quotes (double or single) not being finished, though.

**Comment by mrleblanc101** [comment]
As you've seen, it doesn't work either in the exemple above that do not have hyphen.

**Comment by urbgimtam** [comment]
Sorry then. Can't help you.
I've been using svg's with inline animations without issues, but they are usually with `<animateTransform />` tags.

**Comment by urbgimtam** [comment]
The animation doesn't work when you load it with`?raw`?

> Is there a technical reason why ?inline wouldn't work but ?raw would ?

There may be, as the inline seems to be sensible to white spaces.

**Comment by ttillberg** [comment]
this hasn't been solved in 3 years and I haven't been using the plugin for about that long but remember the workaround was to extract the `<style>` into a css class outside the SVG
