### ISSUE TITLE
The CSS in the SVG is not processed when Nuxt is compiled

### ISSUE THREAD

**Issue by frbuceta** [nuxt-community/svg-module#24]
I am using an SVG with this tag:
`<defs><style>.cls-1{fill:#fff;fill-rule:evenodd;}</style></defs>`

And when I compile the application this tag is empty, the style disappears
It is an SVG generated with illustrator

**Comment by urbgimtam** [comment]
This is a big issue for complex svgs. Anyone has a solution?

**Comment by Geminii** [comment]
Hi, got the same problem 😞

**Comment by jsbroks** [comment]
Same issue here. This is a big problem.

**Comment by jsbroks** [comment]
```html
<img src="~assets/graphics/data.svg?raw" />
```
Using this method it works correctly

**Comment by brhx** [comment]
Please use `raw-loader` as outlined [here](https://github.com/nuxt-community/svg-module#raw-loader) to ensure CSS is imported correctly.
