### ISSUE TITLE
initialy loads urls as [object Module]

### ISSUE THREAD

**Issue by laSinteZ** [nuxt-community/svg-module#3]
## Description
At the initial screen render, img's src are loaded as "[object Module]"
![screen shot 2019-01-16 at 13 05 20](https://user-images.githubusercontent.com/10958990/51241733-78402c00-198f-11e9-833e-a49077204ffa.png)

Problem disappears if you try to edit a file and save it, so page hot-reloads and reappears after usual page reload.

# How to repeat
https://github.com/laSinteZ/nuxt-svg-bug
```
yarn
yarn dev
```
Look at the broken link, try editing nuxt page, try reloading page.

**Comment by laSinteZ** [comment]
Same happens with `<img src="~/assets/example.svg?data">`

**Comment by laSinteZ** [comment]
I've checked previous version, `0.1.4`, and it worked perfectly there. Downgraded for now.

**Comment by brhx** [comment]
Thank you for such a comprehensive bug report! I'm sorry this has happened, I'll unpublish `0.2.0` to bring it back to the latest version and then work out the bugs and redeploy it.

**Comment by brhx** [comment]
I'm sorry for the delay on solving this, I'll be able to get to this later this week.
