### ISSUE TITLE
Installing from NPM does not correlate to the latest version (0.1.6)

### ISSUE THREAD

**Issue by thisischrisj** [nuxt-community/svg-module#31]
After installing from NPM, the contents of `lib/modules.js` does not correlate with those on the repo or documentation. The block concerning `raw-loader` is not present

**Comment by ChristianBielak** [comment]
I think they missed to publish the new release on npmjs. As small workaround i forked the package and published the release with raw loader on npmjs

Hope thats ok :)

https://www.npmjs.com/package/@chrisbielak/svg-module

**Comment by brhx** [comment]
My apologies on the delay on this guys. The package has now been updated and published! Please let me know if there are any issues.
