### ISSUE TITLE
file-loader 6.x breaks imports

### ISSUE THREAD

**Issue by simllll** [nuxt-community/svg-module#40]
They have changed esModule flag to default for url, file and othhers in newer versin of the libraries, therefore includes of assets have now a .default with the new file loader. I didn't figure out why this is a problem with nuxt, but it definitely does not work with the newer file-loader (or url-loader).

They have also the older version for these two packages in their webpack package.json file:
https://github.com/nuxt/nuxt.js/blob/dev/packages/webpack/package.json

Therefore the latest release breaks our images with the lerna repo we have.
Correspoińding commit is https://github.com/nuxt-community/svg-module/commit/3431b9671351e0c2470502ded1784520b6901281

Furthermore I'm also unsure if the newer vue-svg-loader actually works. see https://github.com/visualfanatic/svg-to-vue/issues/19. We couldn't get it running on our side at least (maybe it's related to all the older url and file loaders?)

Anyone else having troubles with this? Can we downgrade the packages again to get this working with nuxt?

**Comment by simllll** [comment]
As a workaround it helps to add 	
	"file-loader": "^4.3.0",
 "url-loader": "^2.3.0",

in your dev dependencies to explicity use the older versions of the modules for nuxt.

**Comment by brhx** [comment]
I believe I've fixed this in 6b2139f291938612386f6175cff45a31c001a349, please update to to `v0.1.9` and let me know if you have any questions!
