### ISSUE TITLE
Usage in storybook and a custom webpack config

### ISSUE THREAD

**Issue by tonioriol** [nuxt-community/svg-module#43]
Using storybook with a custom webpack config and this package i had to add that to the `.storybook/webpack.config.js`:

```
const svgRule = config.module.rules.find(rule => rule.test.test('.svg'));

  svgRule.test = /\.(png|jpe?g|gif|webp)$/;

  config.module.rules.push({
    test: /\.svg$/,
    use: [
      'babel-loader',
      'vue-svg-loader',
    ],
  });
```

I was getting that error otherwise (only in storybook):

```
Invalid Component definition: static/media/somefile.svg
```

**Comment by brhx** [comment]
Hi! I'm afraid storybook isn't natively supported right now. If there is enough interest for this feature then a PR is always welcome :)

**Comment by tonioriol** [comment]
yeah, just wanted to write it down in case someone encounters the same issue :)
