### ISSUE TITLE
[object Module] instead of src value

### ISSUE THREAD

**Issue by mkrajinov** [nuxt-community/svg-module#45]
Hi, I just update Nuxt to 2.18.2 and realize that svgs are not loading anymore. Instead of src path, I'm getting [object Module] value

**Comment by brhx** [comment]
Hi, which version are you using? If you're not using the latest version, please try `0.1.11` (I think I fixed the issue you're having yesterday).

**Comment by mkrajinov** [comment]
Hi, I have already 0.1.11, loading from static is ok, but for assets is not working.

**Comment by brhx** [comment]
Please could you provide a working reproduction link so I can take a look?

**Comment by krajinovicm** [comment]
Here https://dev.rtvglasdrine.com/
A logo is not loading

**Comment by brhx** [comment]
Sorry, I meant a minimal working reproduction link to a codepen or something so I can see all of the relevant code you've been using. I can't diagnose much from a compiled website! 😄

**Comment by krajinovicm** [comment]
Sorry, here is complete repo https://github.com/krajinovicm/rtvglasdrine

**Comment by taro-0** [comment]
Hi, we found this problem as Well. The latest version we were using didn't have this problem. It was only now that we upgraded to the most recent version that this problem came through.

I want to say that our team tried to downgrade the package but it didn't work

**Comment by taro-0** [comment]
@krajinovicm i see you're using the fontawesome svg icon package along with the nuxt/svg package. @sam3d I want to add that we are using nuxt/svg-sprite along with these package. It might be that both packages change the default behaviour for how nuxt loads svg images

**Comment by brhx** [comment]
Ooh that’s interesting, thank you for that note! It could very well likely be that it’s not compatible with `svg-sprite`. I’ll take a look into it and see if I can make them compatible with each other.

**Comment by taro-0** [comment]
@sam3d thank you very much! I see that under the hood this module uses `vue-svg-loader`. I remember that at some point we had problem using a configuration for `vue-svg-loader` would it help a sample of our nuxt configuration for how we solved that problem?

**Comment by mkrajinov** [comment]
I can confirm that something with fontawesome caused issue for me. I did remove fontawesome and loading from assets started working well. Then I have added fontawesome again, and the issue is still not there anymore.

**Comment by ballonura** [comment]
Any solution ?
