### ISSUE TITLE
Handle unique IDs

### ISSUE THREAD

**Issue by tatemz** [nuxt-community/svg-module#48]
If I include the same inline svg in two places, and it uses IDs (e.g. for a mask), then this will cause the second instance of the SVG to be invalid.

More info here:
https://css-tricks.com/youre-inlining-svg-icons-deal-unique-titles-ids/

`vue-svg-loader` already addresses this issue and has some examples of configuration to solve for it
https://github.com/visualfanatic/vue-svg-loader/issues/60

**Comment by manuelodelain** [comment]
Now the `vue-svg-loader` configuration is available through the options https://github.com/nuxt-community/svg-module#configuration
