### ISSUE TITLE
Docker can't find @nuxtjs/svg

### ISSUE THREAD

**Issue by soaresdude** [nuxt-community/svg-module#51]
I run NuxtJS on a docker container (more as a habit than a necessity) and I'm getting the following error when I run `yarn dev` inside the container with docker-compose:
`FATAL  Module @nuxtjs/svg not found. Please ensure @nuxtjs/svg is in dependencies and installed.`

Of course, I have the module installed and that error doesn't happen when I run `yarn dev` outside the container.

PS.: I've already checked and `@nuxtjs/svg` is installed inside the container

**Comment by AllanOricil** [comment]
Could you create an image of this container and publish in a public repository ? Then we can run and see what is the error. Maybe the problem is a Volume configuration?

**Comment by soaresdude** [comment]
> Could you create an image of this container and publish in a public repository ? Then we can run and see what is the error. Maybe the problem is a Volume configuration?

I've solved this but I don't know how :joy: I think it was some update some time after I wrote this question.
