### ISSUE TITLE
Support for Sprites

### ISSUE THREAD

**Issue by kahl-dev** [nuxt-community/svg-module#6]
First of all thank you for the nice module. It would be awesome if you can implement the sprite functionality from your vue-svg module.

**Comment by brhx** [comment]
You're welcome! And I'm afraid I'm super busy at the moment, but this is something I'd like to see. When I get time to get around to it I'll implement it, in the meantime PR's are always welcome! 😄

**Comment by brhx** [comment]
Closing as it's been a while since this has been requested. Please leave a comment or PR if this feature is still of interest :)

**Comment by patrickcate** [comment]
I’d love to see this feature added. Maybe you could leverage https://github.com/JetBrains/svg-sprite-loader ?

**Comment by Lindar90** [comment]
+1 I'd also love this feature
