### ISSUE TITLE
Add support for dynamic sources for vue-svg-loader and raw-loader

### ISSUE THREAD

**Issue by Rednas83** [nuxt-community/svg-module#69]
Great work on this svg loader

With file-loader and url-loader you can have a dynamic source for the svg file.

Something like:
```
<template>
  <img :src=`~assets/${name}.svg` />
</template>
```

Is this also possible with vue-svg-loader and raw-loader?

**Comment by Rednas83** [comment]
Already figured it out
```
<template>
    <div v-html="require(`../assets/${name}.svg?raw`)" />
</template>
```
Perhaps something for the readme?

**Comment by christian-reichart** [comment]
This saved me a lot of headache! Thanks!

**Comment by brhx** [comment]
Hi @Rednas83 thank you for isolating this issue! I'd be very happy to merge a PR with doc amends.
