### ISSUE TITLE
Need dynamic import without wrapper element

### ISSUE THREAD

**Issue by christian-reichart** [nuxt-community/svg-module#72]
Hi, great tool! It really helps me out big time!

I have a issue/question:

I'm loading a dynamic content like so:

```<div v-html="require(`~/assets/img/svg/${name}-clip-path.svg?raw`)" />```

The output then looks something like this:
```
<div data-v-3eaea9aa="">
<!-- the actual svg code -->
</div>
```

How can I make it that only the actual SVG contents are rendered, not the wrapping div?

Thanks in advance for any hints

**Comment by christian-reichart** [comment]
Currently found a quick and hacky way inside `mounted()`, which seems to work:

```
    removeWrapperDiv () {
      const wrapper = this.$refs.wrapper
      if (wrapper) {
        wrapper.parentNode.innerHTML = wrapper.innerHTML
      }
    }
```

Let me know if you have a better solution.

**Comment by mrleblanc101** [comment]
Use `?inline` and `<component :is=require() />`
