### ISSUE TITLE
help proposal

### ISSUE THREAD

**Issue by manuelodelain** [nuxt-community/svg-module#79]
Hi @sam3d we (@ambroisemaupate and myself) would be happy to help you to maintain this lib.
Would you be interested?

**Comment by sam3d** [comment]
Hi Manuel, that would be amazing! Thank you so much, I'll add you both as maintainers now

**Comment by brhx** [comment]
Hi Manuel, thank you so much! ❤️  I'll add you both as maintainers now, I'm afraid I don't have permissions to add you on NPM but I'll happily publish any releases you need

**Comment by manuelodelain** [comment]
Thank you @sam3d !

**Comment by manuelodelain** [comment]
@sam3d I'm sorry but the invitation has expired (sorry for the late reply!). Could you send it again please?

**Comment by brhx** [comment]
No worries, sent again!

**Comment by mrleblanc101** [comment]
Hi, I just opened #82 which fix #74
