### ISSUE TITLE
Not working with "shortcut" path in Nuxt

### ISSUE THREAD

**Issue by pierremouchan** [nuxt-community/svg-module#8]
Hello,
First of all, thanks you for this amazing module :) but it's seems to not work with these 'shortcut' path that Nuxt offer us.. when i just use :
`<img src="~/static/images/icons/logo.svg" alt="" />` --> Working
`<img src="images/icons/logo.svg" alt="" />` --> Not working
`<img src="~/static/images/icons/logo.svg?data" alt="" />` --> Working
`<img src="images/icons/logo.svg?data" alt="" />` --> Not working

It's seems that nuxt-svg doesn't handle correctly these 'direct' path (idk how to call them) to access our images. Is this possible to add it in future release ? :) (Or do you have an idea to solve this problem).
 thank you

**Comment by brhx** [comment]
Thank you for your issue! I'll be able to take a look at this in the next couple of days.

**Comment by brhx** [comment]
Hi! Sorry for the late reply, I don't believe this is supported by default in Nuxt.js, though please let me know if this isn't the case (doc example) and I'll come back to it :)
