### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by manuelodelain** [nuxt-community/svg-module#83]
Hi @sam3d ! Could you publish the new version to npm please? I don't know how we could communicate more smoothly for the npm releases ^^

**Comment by brhx** [comment]
Hi! All published, please feel free to drop me an email so I can jump right on it

**Comment by mrleblanc101** [comment]
@sam3d Hi, could it be possible to create a release in Github and a tag too ? Still state 0.1.2 instead of 0.2.0

**Comment by manuelodelain** [comment]
@mrleblanc101 there is already a v02.0 tag (from 2019). I think we have to bump to v0.3.0 for having a proper release.

**Comment by mrleblanc101** [comment]
Yeah that's odd, the 0.2.0 was release before 1.5.0 through 1.12
