### ISSUE TITLE
Bundling to parent module

### ISSUE THREAD

**Issue by alex-artigas-housfy** [nuxt-community/svg-module#87]
So far I've managed to either get my app.js bloated with hundreds of svgs or getting hundreds of single bundles for each svg. Neither of these are good practices. Is there a way to append each svg to the bundle where it is used?

Thanks!

**Comment by ambroisemaupate** [comment]
Hello @alex-artigas-housfy 
Could you provide a bit more context about your issue? 

If your app uses lots of SVGs it could be better to use [`file-loader`](https://github.com/nuxt-community/svg-module#file-loader) to improve atomicity of your code and to take advantage of browser cache. Loading lots of tiny `.svg` files should not be an issue if your app is running over HTTP/2.
