### ISSUE TITLE
Question: does inline loading affect bundle size?

### ISSUE THREAD

**Issue by jorrit-g** [nuxt-community/svg-module#89]
I'm trying to write a component lib in a nuxt project and we're using this module to load SVGs. 

Currently each page is loading its own SVGs but I want to move to a single "Icon" component which controls the loaded SVG through a prop "variant", see below. 

```
<template>
	<div>
		<Icon1 v-if="variant === 'icon-1'"></Icon1>
		<Icon2 v-if="variant === 'icon-2'"></Icon2>
	</div>
</template>

<script>
import Icon1 from "~/assets/icons/icon-1.svg?inline";
import Icon2 from "~/assets/icons/icon-2.svg?inline";

export default {
	components: {
                 Icon1, 
                 Icon2
	},
	props: {
		variant: {
			type: String,
			required: true,
		},
	},
};
</script>
```

We have about 200 icons which would all be made available in this component. They would all be inlined. 

We would use this component on many pages. My fear is now that each page will get all the svg source of all 200 icons. 
Hereby I assume that an 'inline' svg is somehow fully contained in the javascript bundle.

Am i correct?

**Comment by rchl** [comment]
You can analyze the bundle using https://nuxtjs.org/docs/configuration-glossary/configuration-build/#analyze

You will see exactly what's happening then and whether icons would be duplicated or not (I don't think they would)
