### ISSUE TITLE
Dynamic import for external urls

### ISSUE THREAD

**Issue by OlesyaKohivchak** [nuxt-community/svg-module#94]
We receive svg images from CMS and dynamic import doesn't works in this case, works only for svg images stored in the project.
So is it possible to use external urls somehow?

![image](https://user-images.githubusercontent.com/22976204/194018110-28359053-82ee-445d-a1c7-f10a80416ed4.png)

**Comment by manuelodelain** [comment]
You can't `require()` external URL. If you need an inline SVG from a CMS, you have to fetch the SVG data and then inject it with the `v-html` directive.
